error[E0477]: the type `[closure@src/core/game_window.rs:100:24: 140:10]` does not fulfill the required lifetime    --> src/core/game_window.rs:100:20